// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SSO_Irica.Infrastructure.Persistence;

#nullable disable

namespace IAM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SsoDbContext))]
    [Migration("20260823062525_AlignIamErd")]
    partial class AlignIamErd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SSO_Irica.Domain.Identity.SsoUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Fld_Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Fld_Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_FirstName");

                    b.Property<int?>("GenderId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_LastName");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Fld_Mobile");

                    b.Property<string>("NationalCodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Fld_UserName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("Fld_Password");

                    b.HasKey("Id");

                    b.HasIndex("NationalCodeValue")
                        .IsUnique();

                    b.ToTable("Tbl_User", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.ActionLogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("Fld_Entity_Id");

                    b.Property<int>("ModulesId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Modules_Id");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Actions_Log", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.GenderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_Title");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Gender", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.ModuleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Fld_Code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Fld_Title");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tbl_Modules", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.OrganizationTypeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsActive");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Fld_Title");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tbl_Organization_Type", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.OrganizationUnitRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsActive");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Parent_Id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_Title");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Type_Id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tbl_Organization_Unit", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.PermissionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Fld_Code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_Title");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tbl_Permissions", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.PositionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Fld_Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsActive");

                    b.Property<int>("OrganizationUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Org/Unit_Id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_Title");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Tbl_Positions", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.RolePermissionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsActive");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Module_Id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Permision_Id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Role_Id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ModuleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("Tbl_Role_Permissions", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.RoleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Fld_Title");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Roles", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.UserPositionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fld_EndDateTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsActive");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("Fld_IsPrimary");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Position_Id");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fld_StartDateTime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Fld_User_Id");

                    b.HasKey("Id");

                    b.ToTable("Tbl_User_Positions", (string)null);
                });

            modelBuilder.Entity("SSO_Irica.Infrastructure.Persistence.UserRoleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Fld_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("Fld_Role_Id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Fld_User_Id");

                    b.HasKey("Id");

                    b.ToTable("Tbl_User_Roles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
